// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADrywN6XB3wsrL7t3TCeQWegkUI0RCa3Y',
    appId: '1:161629204198:web:5d528eedada7e87d9f9527',
    messagingSenderId: '161629204198',
    projectId: 'flutterchatpro-f3011',
    authDomain: 'flutterchatpro-f3011.firebaseapp.com',
    storageBucket: 'flutterchatpro-f3011.firebasestorage.app',
    measurementId: 'G-6GBR6QHR1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKE8wpKDASYUUmPWA1PcnVOCqTnTVHIfY',
    appId: '1:161629204198:android:74aae8b57ea870239f9527',
    messagingSenderId: '161629204198',
    projectId: 'flutterchatpro-f3011',
    storageBucket: 'flutterchatpro-f3011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjIA7ZQTGoNZAixrAhkhXXn9vHSpR2bbk',
    appId: '1:161629204198:ios:eec53d6345445d969f9527',
    messagingSenderId: '161629204198',
    projectId: 'flutterchatpro-f3011',
    storageBucket: 'flutterchatpro-f3011.firebasestorage.app',
    iosBundleId: 'com.phitthayarat.chatpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjIA7ZQTGoNZAixrAhkhXXn9vHSpR2bbk',
    appId: '1:161629204198:ios:8dc9c5cb84c301c89f9527',
    messagingSenderId: '161629204198',
    projectId: 'flutterchatpro-f3011',
    storageBucket: 'flutterchatpro-f3011.firebasestorage.app',
    iosBundleId: 'com.example.chatPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADrywN6XB3wsrL7t3TCeQWegkUI0RCa3Y',
    appId: '1:161629204198:web:7476b1f8d40b574c9f9527',
    messagingSenderId: '161629204198',
    projectId: 'flutterchatpro-f3011',
    authDomain: 'flutterchatpro-f3011.firebaseapp.com',
    storageBucket: 'flutterchatpro-f3011.firebasestorage.app',
    measurementId: 'G-K63FWM9JXE',
  );
}
